import React from 'react';
import { SystemMetrics, ComponentEvaluation } from '../types';
import {
  AlertTriangle,
  ShieldAlert,
  Clock,
  ArrowRight,
  Filter,
  CheckCircle2,
  ExternalLink
} from 'lucide-react';

interface RiskAlertsViewProps {
  metrics: SystemMetrics | null;
  currentHour: number;
  selectedComponentId: string;
  onSelectComponent: (cid: string) => void;
  onOpenEvidenceModal: () => void;
  onNavigateTab: (tab: string) => void;
}

export const RiskAlertsView: React.FC<RiskAlertsViewProps> = ({
  metrics,
  currentHour,
  selectedComponentId,
  onSelectComponent,
  onOpenEvidenceModal,
  onNavigateTab
}) => {
  const components = metrics?.components ?? [];

  // Filter real components flagged by the dynamic anomaly engine
  const flaggedAlerts = components.filter(
    (c) => c.decision === 'HOLD / REVIEW' || c.decision === 'WATCH' || c.absolute_status === 'BREACHED'
  );

  const criticalCount = components.filter(
    (c) => c.decision === 'HOLD / REVIEW' || c.absolute_status === 'BREACHED'
  ).length;

  const warningCount = components.filter((c) => c.decision === 'WATCH').length;

  const handleAlertClick = (cid: string) => {
    onSelectComponent(cid);
    onNavigateTab('forensics');
  };

  return (
    <div className="space-y-6 max-w-[1600px] mx-auto pb-8">
      {/* Top Header Card */}
      <div className="bg-white border border-slate-200/90 rounded-2xl p-5 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <span className="w-2 h-2 rounded-full bg-rose-600 animate-pulse" />
            <h2 className="text-lg font-bold font-mono text-slate-900 tracking-tight leading-none">
              RELIABILITY RISK ALERTS CENTER
            </h2>
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-rose-50 text-rose-700 border border-rose-200">
              DYNAMIC LOT TRIAGE
            </span>
          </div>
          <p className="text-xs text-slate-500 font-medium mt-1">
            Real-time notifications generated by Module A & Module B dynamic gates. Click any alert to inspect forensics.
          </p>
        </div>

        {/* Severity Summary Pills */}
        <div className="flex items-center space-x-2.5 font-mono text-xs">
          <div className="px-3 py-1.5 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 font-bold flex items-center space-x-1.5">
            <ShieldAlert className="w-3.5 h-3.5" />
            <span>{criticalCount} Critical Holds</span>
          </div>
          <div className="px-3 py-1.5 rounded-xl bg-amber-50 border border-amber-200 text-amber-800 font-bold flex items-center space-x-1.5">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>{warningCount} Watch Warnings</span>
          </div>
        </div>
      </div>

      {/* Alert Table */}
      <div className="bg-white border border-slate-200/90 rounded-2xl overflow-hidden shadow-xs">
        <div className="px-5 py-3.5 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
          <div className="flex items-center space-x-2">
            <Filter className="w-3.5 h-3.5 text-slate-400" />
            <span className="text-xs font-bold font-mono text-slate-700 uppercase tracking-wider">
              Active Triage Queue ({flaggedAlerts.length} Flagged Devices)
            </span>
          </div>
          <span className="text-xs font-mono text-slate-400">
            Hour: {currentHour.toFixed(0)}h / 168h
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead>
              <tr className="border-b border-slate-200/80 bg-slate-50/80 text-slate-500 font-semibold uppercase text-[10px] tracking-wider">
                <th className="py-3 px-4">Severity</th>
                <th className="py-3 px-4">Component ID</th>
                <th className="py-3 px-4">Lot ID</th>
                <th className="py-3 px-4">Burn-in Hour</th>
                <th className="py-3 px-4">Screening Reason & Anomaly Types</th>
                <th className="py-3 px-4">Triage Status</th>
                <th className="py-3 px-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {flaggedAlerts.length > 0 ? (
                flaggedAlerts.map((a) => {
                  const isCritical = a.decision === 'HOLD / REVIEW' || a.absolute_status === 'BREACHED';
                  const isSelected = a.component_id === selectedComponentId;
                  const reasonText =
                    a.anomaly_types && a.anomaly_types.length > 0
                      ? a.anomaly_types.join(', ')
                      : 'Lot-Relative Parameter Divergence';

                  return (
                    <tr
                      key={a.component_id}
                      onClick={() => handleAlertClick(a.component_id)}
                      className={`cursor-pointer transition-colors duration-150 ${
                        isSelected
                          ? 'bg-blue-50/70 hover:bg-blue-50'
                          : 'hover:bg-slate-50/80'
                      }`}
                    >
                      {/* Severity */}
                      <td className="py-3.5 px-4 whitespace-nowrap">
                        <span
                          className={`px-2 py-0.5 rounded text-[10px] font-bold border ${
                            isCritical
                              ? 'bg-rose-50 text-rose-700 border-rose-200'
                              : 'bg-amber-50 text-amber-800 border-amber-200'
                          }`}
                        >
                          {isCritical ? 'CRITICAL' : 'WARNING'}
                        </span>
                      </td>

                      {/* Component ID */}
                      <td className="py-3.5 px-4 font-bold text-slate-900 whitespace-nowrap">
                        {a.component_id}
                        {a.component_id === 'C-104' && (
                          <span className="ml-1.5 px-1 py-0.2 rounded text-[9px] bg-blue-100 text-blue-800 border border-blue-200">
                            BENCHMARK
                          </span>
                        )}
                      </td>

                      {/* Lot ID */}
                      <td className="py-3.5 px-4 text-blue-700 font-semibold whitespace-nowrap">
                        {a.lot_id}
                      </td>

                      {/* Burn-in Hour */}
                      <td className="py-3.5 px-4 text-slate-600 whitespace-nowrap">
                        {currentHour.toFixed(0)}h
                      </td>

                      {/* Reason */}
                      <td className="py-3.5 px-4 text-slate-700">
                        <div className="font-medium text-slate-800 truncate max-w-md">
                          {reasonText}
                        </div>
                        <div className="text-[10px] text-slate-400 mt-0.5">
                          Abs Limit: {a.absolute_status} • Lot Dev: {a.lot_deviation_score ?? 'N/A'}/100
                        </div>
                      </td>

                      {/* Triage Status */}
                      <td className="py-3.5 px-4 whitespace-nowrap">
                        <span
                          className={`px-2 py-0.5 rounded text-[10px] font-bold border ${
                            isCritical
                              ? 'bg-rose-50 text-rose-700 border-rose-200'
                              : 'bg-amber-50 text-amber-800 border-amber-200'
                          }`}
                        >
                          {a.decision}
                        </span>
                      </td>

                      {/* Action */}
                      <td className="py-3.5 px-4 text-right whitespace-nowrap">
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleAlertClick(a.component_id);
                          }}
                          className="inline-flex items-center space-x-1 px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-blue-50 text-slate-700 hover:text-blue-700 border border-slate-200 transition text-[11px] font-bold"
                        >
                          <span>Forensics</span>
                          <ArrowRight className="w-3 h-3" />
                        </button>
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td colSpan={7} className="text-center py-12 text-slate-400 font-mono text-xs">
                    No active risk alerts at current burn-in hour.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
